### ISSUE TITLE
你好，这个方案还会继续更新吗

### ISSUE THREAD

**Issue by zhouchaozhi** [siliconx/e_commerce#1]

**Comment by siliconx** [comment]
应该不会了，这个baseline是给计算机硕士一年级选机器学习课程的学生参考的，现在他们的课已经上完了

**Comment by zhouchaozhi** [comment]
哦哦。谢谢。那我想问一下，这个预测值一定是商品id嘛？是否可以用二分类，取购买概率值最高的商品当作下一个要购买的商品嘛？
