### ISSUE TITLE
建模问题。

### ISSUE THREAD

**Issue by zhouchaozhi** [siliconx/e_commerce#2]
哦哦。谢谢。那我想问一下，这个预测值一定是商品id嘛？是否可以用二分类，取购买概率值最高的商品当作下一个要购买的商品嘛？

**Comment by siliconx** [comment]
可以啊，只是lgb直接把预测结果给出来了，本质是一样的，不过概率是多分类的概率

**Comment by zhouchaozhi** [comment]
好的。谢谢
